---
# tasks file for db
- name: Creates directory for db role 
  file:
    path: /home/vagrant/db
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0770'

- name: Copy db configs
  copy: src={{item.src}} dest={{item.dest}}
  loop:
    - {src: 'docker-compose.yml', dest: '/home/vagrant/db/docker-compose.yml'}

- name: reset ssh connection 
  meta: reset_connection

- name: Run container
  shell:
    chdir: /home/vagrant/db
    cmd: "docker-compose -f docker-compose.yml up -d"
