---
# tasks file for nginx
- name: Copy role files # Копируем файлы роли на хост 
  copy: src=nginx dest=/home/vagrant

- name: reset ssh connection 
  meta: reset_connection

- name: Run container
  shell:
    chdir: /home/vagrant/nginx
    cmd: "docker-compose -f docker-compose.yml up -d"
