---
# tasks file for nodejs
- name: Copy role files # Копируем файлы роли на хост 
  copy: src=node dest=/home/vagrant

- name: reset ssh connection 
  meta: reset_connection

- name: Run container
  shell:
    chdir: /home/vagrant/node
    cmd: "docker-compose -f docker-compose.yml up -d"