---
# tasks file for ctfd
    
- name: Clone a CTFd repo
  ansible.builtin.git:
    repo: https://github.com/CTFd/CTFd.git
    dest: /home/vagrant/CTFd
  ignore_errors: yes
  
- name: Copy role files # Копируем файлы роли на хост 
  copy: src=CTFd dest=/home/vagrant

- name: reset ssh connection 
  meta: reset_connection

- name: Run container
  shell:
    chdir: /home/vagrant/CTFd
    cmd: "docker-compose -f docker-compose.yml up -d"
