---

- name: 'Provision web hosts'
  hosts: web
  gather_facts: true
  become: true
  roles:
    - common
    - docker-host
    - docker-node
    - docker-wordpress
    - docker-ctfd
    - docker-nginx
